### ISSUE TITLE
Same day, same user, different IPs

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog-plugin-geoip#10]
I was doing some testing in PostHog that involves IP addresses, and noticed that my location was indicated as San Francisco (when it should be New York).

Some events on PostHog also had an IP address that was not my own. (There are at least 2 other IPs besides my own home address). I would also be surprised if these were "hops" on my ISP because I would assume that based on my physical location, I would be connected to a server in N. Virginia or similar.

No proxies or VPNs that I know of are configured on my network.

**Comment by Twixes** [comment]
Hmm, the question is, where these other events actually 100% you? We've seen some weirdness like my Marius's event going to my PostHog person recently, which is a more core data integrity problem than wrong IP (as I'm not aware of this plugin being capable of switching the IP).

**Comment by samwinslow** [comment]
Ah! Yeah, that's much more likely to be the case, since looking at it now there were some pageviews on URLs I never visited.

Is there an issue open for that? Will happily close this out + add more info there.

**Comment by Twixes** [comment]
I think #134 may be relevant here. Will close this, as doesn't look like a plugin issue in any case.
