### ISSUE TITLE
Dump GeoIP data by event name or other property

### ISSUE THREAD

**Issue by januwland** [PostHog/posthog-plugin-geoip#18]
I've got segment as a library sending events into PostHog, but not all libraries within segment are created equal and server events are firing with fixed American IP address (we're in Australia), giving me questionable data in PostHog.

I'd like to enable GeoIP for strictly either a fixed set of events, or a sub-library of segment. Maybe if PostHog ingested Segment library as an object then I could enable client, and drop server.

In general this plugin is fantastic but somewhat unusable if half of the sources are getting 'wrong' information.

**Comment by weyert** [comment]
@januwland Would the `$geoip_disabled` approach not work for  you?
