### ISSUE TITLE
Doesn't work when setting "Discard client IP data"

### ISSUE THREAD

**Issue by boldtrn** [PostHog/posthog-plugin-geoip#6]
Due to the GDPR I use the setting "Discard client IP data". However, I am not getting any results from the plugin.

Not sure if it would be possible to discard the client IP after the plugin fetched the geoip?

**Comment by Twixes** [comment]
Hey! This is unfortunately not really possible at the moment, because if plugins still had access to the IP of the user, export plugins for instance would also export the IP, nullifying the setting in a way. So for now, it's either IPs all the way, or not at all.

**Comment by boldtrn** [comment]
Thanks, that makes sense. Maybe that might be supported in the future :)
