### ISSUE TITLE
Skip Geolocation and/or Custom IP override

### ISSUE THREAD

**Issue by phil-monroe** [PostHog/posthog-plugin-geoip#7]
It would be great if we can opt-out of GeoIP classification on an as-needed basis. In our use case, we record some events from the browser side (Posthog JS) and some events from our server side (Posthog Ruby). All server-side events end up appearing from Ashburn, Virginia (eg: AWS `us-east-1`) and we are unable to prevent the data from being tainted for the Person profiles. I think it would be great if the following could be added:

- [x] Guard clause to skip GeoIP lookup if the `$geoip_enabled` event property is set to `false`.
- [x] Attempt to lookup the IP to geolocate based on the `$ip` property and fallback to `event.ip` if IP address is not explicitly set.

**Comment by Twixes** [comment]
Hey! Sure, solved with #8. Read https://github.com/PostHog/posthog-plugin-geoip#readme now. :)

**Comment by phil-monroe** [comment]
Thanks for the super speedy response, @Twixes!
